"""Reference stub for ``nbnt_example_hello``.

Regenerate with:

    python -m nanobind_namedtuple_stubgen -m nanobind_namedtuple_examples.nbnt_example_hello -o examples/hello.pyi

The ``typing.NamedTuple`` classes are produced by the stubgen extension shipped
in ``stubgen/nanobind_namedtuple_stubgen``; a plain ``python -m nanobind.stubgen``
run would emit ``class X(tuple): ...`` blocks instead.
"""

import types
from collections.abc import Sequence
from typing import NamedTuple

def hello() -> str: ...
def add(arg0: int, arg1: int, /) -> int: ...

class Color(NamedTuple):
    r: float
    g: float
    b: float

class Point(NamedTuple):
    """A 2D point with an optional display label."""

    x: int
    """X coordinate."""
    y: int
    label: str = ""
    """Display label."""

class Empty(NamedTuple):
    pass

class Vec3(NamedTuple):
    x: float
    y: float
    z: float

class Payload(NamedTuple):
    obj: object

class Pixel(NamedTuple):
    position: Vec3
    color: Color

class Tagged(NamedTuple):
    value: int
    tag: int | None = None
    """Optional integer tag."""

class Polyline(NamedTuple):
    points: list[tuple[int, int]]
    width: float | None

def rebind_color(arg: types.ModuleType, /) -> None: ...
def make_color(arg0: float, arg1: float, arg2: float, /) -> Color: ...
def sum_color(arg: Color, /) -> float: ...
def make_point(arg0: int, arg1: int, arg2: str, /) -> Point: ...
def point_label(arg: Point, /) -> str: ...
def make_empty() -> Empty: ...
def take_empty(arg: Empty, /) -> bool: ...
def make_vec3(arg0: float, arg1: float, arg2: float, /) -> Vec3: ...
def sum_vec3(arg: Vec3, /) -> float: ...
def make_payload(arg: object, /) -> Payload: ...
def payload_obj(arg: Payload, /) -> object: ...
def make_pixel(arg0: Vec3, arg1: Color, /) -> Pixel: ...
def pixel_color(arg: Pixel, /) -> Color: ...
def pixel_position(arg: Pixel, /) -> Vec3: ...
def make_tagged(arg0: int, arg1: int | None) -> Tagged: ...
def tagged_tag(arg: Tagged, /) -> int | None: ...
def make_polyline(arg0: Sequence[tuple[int, int]], arg1: float | None) -> Polyline: ...
def polyline_points(arg: Polyline, /) -> list[tuple[int, int]]: ...
def make_color_reference(arg0: float, arg1: float, arg2: float, /) -> Color: ...
def make_color_reference_internal(arg0: float, arg1: float, arg2: float, /) -> Color: ...
def make_color_take_ownership(arg0: float, arg1: float, arg2: float, /) -> Color: ...
def make_color_copy(arg0: float, arg1: float, arg2: float, /) -> Color: ...
def make_color_move(arg0: float, arg1: float, arg2: float, /) -> Color: ...
